### ISSUE TITLE
plugins not extracted in case of reinstall

### ISSUE THREAD

**Issue by qeepcologne** [revive-adserver/revive-adserver#1362] opened 2022-03-04 15:19 UTC
in case of reinstall revive adserver on the same domain + same revive version + same database + existing conf file
install/upgrade wizard is skipped.
this results in plugins are not extracted.

i know that i can workaround via:
unzip 'etc/plugins/*.zip' -d .
chown -r www-data:www-data .

install example:
```
class developer::revive {

  # revive adserver
  #
  # this file requires php$php_version.pp, lighttpd.pp and projects.pp already installed
  #
  # after install call webinterface and follow install/upgrade process
  # if there is no change just resetup plugins are not installed, call manually in revive dir
  # unzip 'etc/plugins/*.zip' -d .
  # chown -r www-data:www-data .

  $revive_version = "5.3.1"
  $php_version = "7.4"
  $target_domain = "rvtest.example.org"

  exec { 'curl-revive':
    command	=> "curl -o /projects/local/revive-$revive_version.tar.gz https://download.revive-adserver.com/revive-adserver-$revive_version.tar.gz",
    path	=> '/usr/bin:/usr/sbin:/sbin',
    unless	=> "test -f /projects/local/$target_domain/www/delivery/ajs.php",
    provider	=> shell,
    require	=> [
    			Package['curl'],
			Package["php$php_version-fpm"], Package["php$php_version-zip"],
			File["/projects/local"]
    ],
    notify	=> Exec['extract-revive'],
  }

  exec { 'extract-revive':
    refreshonly	=> true,
    command	=> "cd /projects/local; tar xfz revive-$revive_version.tar.gz; mv revive-adserver-$revive_version $target_domain; chown -hR www-data:www-data $target_domain; rm revive-$revive_version.tar.gz",
    path	=> '/bin:/usr/bin:/usr/sbin:/sbin',
    unless	=> 'test -d /projects/local/$target_domain',
    provider	=> shell
  }

  file { "/projects/local/$target_domain/var/$target_domain.conf.php":
    ensure	=> present,
    source	=> "puppet:///modules/$hostname/projects/local/$target_domain/var/$target_domain.conf.php",
    owner	=> 'www-data',
    group	=> 'www-data',
    mode	=> "0644",
  }

  file{'/projects/local/$target_domain/www/images':
    ensure	=> directory,
    source	=> "puppet:///modules/$hostname/projects/local/$target_domain/www/images",
    recurse	=> true,
    owner	=> 'www-data',
    group	=> 'www-data',
    mode   	=> "0644"
  }

}
```

install.log after accessing webinterface:
```
=========================================================================
Attempting to detect an existing Openads (aka. phpAdsNew) installation...
PAN not detected
Attempting to detect an existing Openads (aka. Max Media Manager 0.1) installation...
MMM v0.1 not detected
Attempting to detect an existing Openads (aka. Max Media Manager 0.3) installation...
MMM v0.3 not detected
Attempting to detect an existing Revive Adserver installation...
Revive Adserver 5.3.1 detected
This version is up to date.
Starting file-check for plugins...
Plugin: openXBannerTypes - Unable to locate XML files
Plugin: openXDeliveryLimitations - Unable to locate XML files
Plugin: openXReports - Unable to locate XML files
Plugin: openXDeliveryCacheStore - Unable to locate XML files
Plugin: reviveMaxMindGeoIP2 - Unable to locate XML files
Plugin: openXInvocationTags - Unable to locate XML files
Plugin: openXDeliveryLog - Unable to locate XML files
Plugin: openXVideoAds - Unable to locate XML files
Finished file-check for plugins
```

https://forum.revive-adserver.com/topic/192-plugin-not-installed/

**Comment by erikgeurts** [comment] 2022-03-04 15:27
Not a bug or any other type of issue, you're just doing something that's never intended. Closing this issue and marking it as invalid.

**Closed by erikgeurts** 2022-03-04 15:27 UTC
Labels: Won't Fix
