### ISSUE TITLE
PHP 7.1.9 - Installation failed

### ISSUE THREAD

**Issue by djob** [revive-adserver/revive-adserver#888] opened 2017-09-22 06:43 UTC
Problem:
Installation failed at script step admin/install.php with following errors:
`
MESSAGE: Only variables should be assigned by reference
TYPE: Notice
FILE: /hosting/versions/adserver/lib/pear/MDB2/Driver/Datatype/Common.php
LINE: 1101
DEBUG INFO:

1096	* a DBMS specific format. 
1097	* @access public 
1098	*/ 
1099	function quote($value, $type = null, $quote = true, $escape_wildcards = false) 
1100	{ 
1101	$db =& $this->getDBInstance();

1102	if (PEAR::isError($db)) { 
1103	return $db; 
1104	} 
1105	
1106	if (is_null($value)
MESSAGE: Non-static method PEAR::isError() should not be called statically
TYPE: Deprecated
FILE: /hosting/versions/adserver/lib/pear/MDB2/Driver/Datatype/Common.php
LINE: 1102
DEBUG INFO:

1097	* @access public 
1098	*/ 
1099	function quote($value, $type = null, $quote = true, $escape_wildcards = false) 
1100	{ 
1101	$db =& $this->getDBInstance(); 
1102	if (PEAR::isError($db)) {

1103	return $db; 
1104	} 
1105	
1106	if (is_null($value) 
1107	|| ($value === '' && $db->options['portability'] & MDB2_PORTABILITY_EMPTY_TO_NULL)
MESSAGE: Only variables should be assigned by reference
TYPE: Notice
FILE: /hosting/versions/adserver/lib/pear/MDB2/Driver/Datatype/Common.php
LINE: 1205
DEBUG INFO:

1200	{ 
1201	if (!$quote) { 
1202	return $value; 
1203	} 
1204	
1205	$db =& $this->getDBInstance();

1206	if (PEAR::isError($db)) { 
1207	return $db; 
1208	} 
1209	
1210	$value = $db->escape($value, $escape_wildcards);
MESSAGE: Non-static method PEAR::isError() should not be called statically
TYPE: Deprecated
FILE: /hosting/versions/adserver/lib/pear/MDB2/Driver/Datatype/Common.php
LINE: 1206
DEBUG INFO:

1201	if (!$quote) { 
1202	return $value; 
1203	} 
1204	
1205	$db =& $this->getDBInstance(); 
1206	if (PEAR::isError($db)) {

1207	return $db; 
1208	} 
1209	
1210	$value = $db->escape($value, $escape_wildcards); 
1211	return "'".$value."'";
MESSAGE: Only variables should be assigned by reference
TYPE: Notice
FILE: /hosting/versions/adserver/lib/pear/MDB2/Driver/Datatype/Common.php
LINE: 1101
DEBUG INFO:

1096	* a DBMS specific format. 
1097	* @access public 
1098	*/ 
1099	function quote($value, $type = null, $quote = true, $escape_wildcards = false) 
1100	{ 
1101	$db =& $this->getDBInstance();

1102	if (PEAR::isError($db)) { 
1103	return $db; 
1104	} 
1105	
1106	if (is_null($value)
MESSAGE: Non-static method PEAR::isError() should not be called statically
TYPE: Deprecated
FILE: /hosting/versions/adserver/lib/pear/MDB2/Driver/Datatype/Common.php
LINE: 1102
DEBUG INFO:

1097	* @access public 
1098	*/ 
1099	function quote($value, $type = null, $quote = true, $escape_wildcards = false) 
1100	{ 
1101	$db =& $this->getDBInstance(); 
1102	if (PEAR::isError($db)) {

1103	return $db; 
1104	} 
1105	
1106	if (is_null($value) 
1107	|| ($value === '' && $db->options['portability'] & MDB2_PORTABILITY_EMPTY_TO_NULL)
MESSAGE: Only variables should be assigned by reference
TYPE: Notice
FILE: /hosting/versions/adserver/lib/pear/MDB2/Driver/Manager/mysqli.php
LINE: 1026
DEBUG INFO:

1021	* @param string $table 
1022	* @return array 
1023	*/ 
1024	function getTableStatus($table) 
1025	{ 
1026	$db =& $this->getDBInstance();

1027	if (PEAR::isError($db)) { 
1028	return $db; 
1029	} 
1030	
1031	$query = "SHOW TABLE STATUS LIKE '{$table}'";
MESSAGE: Non-static method PEAR::isError() should not be called statically
TYPE: Deprecated
FILE: /hosting/versions/adserver/lib/pear/MDB2/Driver/Manager/mysqli.php
LINE: 1027
DEBUG INFO:

1022	* @return array 
1023	*/ 
1024	function getTableStatus($table) 
1025	{ 
1026	$db =& $this->getDBInstance(); 
1027	if (PEAR::isError($db)) {

1028	return $db; 
1029	} 
1030	
1031	$query = "SHOW TABLE STATUS LIKE '{$table}'"; 
1032	$result = $db->queryAll($query, null, MDB2_FETCHMODE_ASSOC);
MESSAGE: Non-static method MDB2::isResultCommon() should not be called statically
TYPE: Deprecated
FILE: /hosting/versions/adserver/lib/pear/MDB2.php
LINE: 2632
DEBUG INFO:

2627	$err =& $this->customRaiseError(MDB2_ERROR_NOT_FOUND, null, null, 
2628	'result class does not exist '.$class_name, __FUNCTION__); 
2629	return $err; 
2630	} 
2631	$result = new $class_name($this, $result, $limit, $offset); 
2632	if (!MDB2::isResultCommon($result)) {

2633	$err =& $this->customRaiseError(MDB2_ERROR_NOT_FOUND, null, null, 
2634	'result class is not extended from MDB2_Result_Common', __FUNCTION__); 
2635	return $err; 
2636	} 
2637	if (!empty($types)) {
`
and many more. 

Steps To Reproduce:
- Deploy fresh 4.0.2 version on server (PHP 7.1.9-1+ubuntu16.04.1+deb.sury.org+1)
- Start install, enter all required data, hit install

**Comment by mbeccati** [comment] 2017-09-22 07:41
Hmm, I have installed it on PHP 7.1 many times without particular issues. My development box runs 7.1 as well.

It looks like you've changed the default configuration setting `production` to false. Or maybe the php configuration is not standard (e.g. blocked functions)?

**Comment by djob** [comment] 2017-09-23 04:58
I checked production parameter:

`production=1`

So is not in debug mode.

Basically the problem is error reporting. My global php.ini error_reporting conf does not allow notices.
Where i can configure error_reporting from app level?

"Or maybe the php configuration is not standard (e.g. blocked functions)?"
It is standard/common clean PHP installation on VPS. 

Long term wise, is there any plan to fix all those notices/deprecated errors?

**Comment by mbeccati** [comment] 2017-09-23 06:12
@djob Could you please (privately) share a phpinfo page?

**Comment by djob** [comment] 2017-09-23 06:31
Here you have: [phpinfo().txt](https://github.com/revive-adserver/revive-adserver/files/1326323/phpinfo.txt)

**Comment by mbeccati** [comment] 2017-09-23 13:42
Cannot replicate, there must be something funny going on your server, or you didn't follow the instructions.

![immagine](https://user-images.githubusercontent.com/282388/30773683-ad5c4638-a075-11e7-9229-8ac34d910a60.png)

Please feel free to ask for help on our forums. I'm closing the issue now, feel free to reopen in case you have evidence it is an actual bug in Revive Adserver.

**Closed by mbeccati** 2017-09-23 13:42 UTC
Labels: Feedback Required

**Comment by djob** [comment] 2017-09-25 05:10
I found what causes the problem. My MySQL password contained following special  characters:
`(#%&")`
one of them caused behavior described above.

It must be a bug somewhere in app level.

**Comment by erikgeurts** [comment] 2017-09-25 06:15
Please provide specific and exact steps to reproduce.
