### ISSUE TITLE
Fatal error with PHP 7

### ISSUE THREAD

**Issue by MarioKnight** [revive-adserver/revive-adserver#654] opened 2015-12-16 13:19 UTC
I have Revive Adserver running on its own VPS with no issues on PHP 5.6.16.  I attempted to update PHP to 7 as I have started to do with other single-use servers, and with Revive Adserver, the following error occurred:

`A fatal error occurred Revive Adserver can't connect to the database. Because of this it isn't possible to use the administrator interface. The delivery of banners might also be affected. Possible reasons for the problem are: <ul> <li>The database server isn't functioning at the moment</li> <li>The location of the database server has changed</li> <li>The username or password used to contact the database server are not correct</li> <li>PHP has not loaded the MySQL Extension</li> </ul>`

The PHP update was the only change, and the MySQL extension was updated with PHP and other PHP components.  I switched back to 5.6.16 and all was well.  Please let me know what the potential issue could be, and if there's anything else I can provide from my end to help better troubleshoot this issue.  Thank you.

**Comment by erikgeurts** [comment] 2015-12-16 13:20
Duplicate of #652 ?

**Comment by andrewatfornax** [comment] 2016-01-06 22:38
@erikgeurts - Agreed, this sounds like a duplicate, and is covered with the documentation update made in #652. I'll close this now, but please update with more info @MarioKnight if you think it's something different. Thanks.

**Closed by andrewatfornax** 2016-01-06 22:38 UTC
Labels: Question
