### ISSUE TITLE
Uploaded image permissions (chmod)

### ISSUE THREAD

**Issue by AceWT** [revive-adserver/revive-adserver#903] opened 2017-10-21 16:22 UTC
Problem:
Uploaded banned image has invalid chmod permissions (0600) and it is not readable by apache.

Steps To Reproduce:
Install on cpanel account where cpanel has obscure security settings.

**Comment by erikgeurts** [comment] 2017-10-21 16:42
Please post your support question on our community forums at https://forum.revive-adserver.com

**Comment by mbeccati** [comment] 2017-10-24 08:05
Sorry, not a bug in Revive Adserver. Closing

**Closed by mbeccati** 2017-10-24 08:05 UTC
Labels: Invalid, Question
