### ISSUE TITLE
Deactivate/Activate Banner is not working

### ISSUE THREAD

**Issue by MrJohnyk** [revive-adserver/revive-adserver#682] opened 2016-03-03 20:40 UTC
I just installed a fresh copy of the script. Trying to deactivate a banner lead to error message "You don't have access to that page. You have been re-directed."

I tried to logout/login, but nothing. The only way to solve the issue is to change directly in database the banner status.
apache 2.2.31 + php 5.6.18 + mysql 5.6.29

Please advice.

**Comment by MrJohnyk** [comment] 2016-03-04 10:09
Today, I have created a new database, installed one more time a fresh copy of the script. Created a test advertiser, a test campaign and a test banner. Everything was running smoothly till this point. However trying to deactivate the banner I get the error message. Most likely it's a bug. 
I have used till now a patched version of the old OpenX without this problem.

**Comment by mbeccati** [comment] 2016-03-04 10:22
Duplicate of #676

**Closed by mbeccati** 2016-03-04 10:22 UTC
