### ISSUE TITLE
Roll out upgrade without accessing web interface

### ISSUE THREAD

**Issue by L3on1d** [revive-adserver/revive-adserver#1074] opened 2019-07-08 11:32 UTC
Hi folks!

I'm looking for solution to roll out updates without accessing web interface, is it possible to automate deployment process? Any ideas? 

Thank you.

**Comment by andrewatfornax** [comment] 2019-07-09 03:58
This is a duplicate of #275. Closing.

**Closed by andrewatfornax** 2019-07-09 03:58 UTC
Labels: Duplicate
