### ISSUE TITLE
MaxMind geo targeting does not support "cellular" value of "netspeed" field

### ISSUE THREAD

**Issue by Zer0Divis0r** [revive-adserver/revive-adserver#812] opened 2017-02-09 15:38 UTC
Continuing this issue: https://github.com/revive-adserver/revive-adserver/issues/792

I have configured Apache's mod_maxminddb, it sets the correct environment variable, it knows to work with GeoIP2 "Connection-Type" database, and it detects connection type perfectly fin. 
I have also set up Revive's oxMaxMindModGeoIP plugin. But still unable to set targeting to "Cellular" in admin UI.

BTW, the oxMaxMindModGeoIP plugin already knows to check $_SERVER['GEOIP_NETSPEED'], it's just UI that does not allow to set this type of limitation.

**Comment by andrewatfornax** [comment] 2018-02-05 22:56
If I can, I will try and look at this for 4.2.0, given that we're aiming to do #315 as part of that release as well.

**Comment by andrewatfornax** [comment] 2019-09-03 12:41
This is really a duplicate of #315, because prior to GeoIP2 support in Revive Adserver, this was never going to work.

Closing as a duplicate, as we expecte #315 to resolve this.

**Closed by andrewatfornax** 2019-09-03 12:41 UTC
Labels: Enhancement
