### ISSUE TITLE
Async tags break IE8

### ISSUE THREAD

**Issue by lid2000** [revive-adserver/revive-adserver#599] opened 2015-07-20 23:58 UTC
We have had problems where the addition of the new async code has caused JS to halt execution in IE8. After poking around a bit, it looks like it's due to the use of Object.keys() in the async.js code. If you change it to something like:

```javascript
var ksize = [];
for (var z in c.reviveAsync) ksize++;
var f = c.reviveAsync[a]={id: ksize...
```

...and change console to window.console then it still won't display the ads, but it won't error out and halt execution of other things.

**Comment by erikgeurts** [comment] 2015-07-21 01:44
Could this be a duplicate of #585

**Comment by mbeccati** [comment] 2015-07-21 07:17
@erikgeurts yes.

**Closed by mbeccati** 2015-07-21 07:17 UTC

**Comment by mbeccati** [comment] 2015-07-21 07:23
@lid2000 could you please try this? https://raw.githubusercontent.com/revive-adserver/revive-adserver/fa799a958ffc5533b370b11994dde8666e00d860/www/delivery/async.js

**Comment by lid2000** [comment] 2015-07-22 00:09
@mbeccati I replaced my modifications with the code you linked to and it
seems to work. Thanks (and apologies for the duplicate - I searched for
similar issues but didn't think to search closed stuff).
