### ISSUE TITLE
Magic Macros are not working with HTML5 zip banners

### ISSUE THREAD

**Issue by idanmet** [revive-adserver/revive-adserver#1338] opened 2021-12-16 02:32 UTC
Seem like the Magic Macros are not working with HTML5 zip uploaded banners, is this the intended behavior?

**Comment by mbeccati** [comment] 2021-12-16 06:49
Most likely it's not the intended behaviour, but no one noticed as zipfiles come from external sources that are not Revive specific. We'll check.

**Comment by erikgeurts** [comment] 2021-12-27 09:35
My guess is that parts of the uploaded HTML5 banner are simply just uploaded and stored as part of the static content, and not processed by Revive Adserver at all, and subsequently simply downloaded by the client as part of the static content, just like images or CSS elements. Hence any macros in them won't be recognized nor processed during delivery. In that sense it's similar to loading an external banner inside an iframe. I don't think there's a lot we can do to fix this.

**Comment by mbeccati** [comment] 2022-01-20 15:21
Closing, @erikgeurts is right and no magic macros can be processed.

**Closed by mbeccati** 2022-01-20 15:21 UTC
