### ISSUE TITLE
500 error after upgrading

### ISSUE THREAD

**Issue by sakshiwadhwa12** [revive-adserver/revive-adserver#1008] opened 2018-10-20 09:22 UTC
After upgrading PHP version to 7.2 adserver is giving 500 error. Here is the link http://restonhosting.com/adserver/www/admin/index.php.
After that, I read somewhere that 7.2 is not supported so downgrade it to 7.0 so i did that too. But its still giving error. Please look into this matter and revert as soon as possible.

**Comment by andrewatfornax** [comment] 2019-03-03 03:32
Hi @sakshiwadhwa12,

The HTTP 500 error code relates to internal errors - generally, something going wrong on the server prior to the execution of the Revive Adserver code.

It's unlikely to be an issue with Revive Adserver itself, and as this is not a bug report with reproduce steps, I am closing the issue.

Should there be feedback from the community in the forums that leads to more information that demonstrates a bug, please feel free to post an update and we can always re-open the issue.

Thanks.

**Closed by andrewatfornax** 2019-03-03 03:32 UTC
