### ISSUE TITLE
javascript error in ox.ui.js:function formFormat(field, allowzero)

### ISSUE THREAD

**Issue by dynamicplus** [revive-adserver/revive-adserver#550] opened 2015-05-12 11:13 UTC
formFormat some times receives undefined on parameter "field"
so later "field.value" assignment crashes.

bug present in v >=3.1 
i have patched this way.

function formFormat(field, allowzero)
{
   if ( !field ) return; /* patch */

**Comment by erikgeurts** [comment] 2015-05-12 12:00
Can you please provide some more detail on where this occurs in the application?

**Comment by dynamicplus** [comment] 2015-05-12 13:48
campaign -> edit (under existing campaign) if campaign is contract-type.
this happens onLoad.

**Comment by erikgeurts** [comment] 2015-05-12 14:00
I'm unable to reproduce this in Revive Adserver 3.2.0. Which version are you using?

**Comment by dynamicplus** [comment] 2015-05-12 22:00
3.2.0.
affected/tested chrome/safari/firefox (lastest) on both windows8.1 and macosx10.10

**Comment by dynamicplus** [comment] 2015-05-12 22:11
this is a screenshot.
as you can se error is preventing correct flelds to be displayed (in this case calendar+start date field as start date is checked).



![screen](https://cloud.githubusercontent.com/assets/2845791/7599680/6fd7c244-f904-11e4-909a-46957d7368e2.png)

**Comment by erikgeurts** [comment] 2015-05-13 06:31
Thanks for your additional information. I am still not able to reproduce this.

Can you please open a pull request for the proposed patch?

**Comment by dynamicplus** [comment] 2015-05-13 17:14
it's just a line of code... really is needed fork+pull request?

**Comment by mbeccati** [comment] 2015-05-18 09:18
@dynamicplus Detailed bug reports and, If you can code, pull requests are a nice way to give back to the project and make its developers' life much easier. If you see it as a waste of *your* time then try to think how much of their spare/unpaid time the developers invest on open source.

That said, I'm not able to replicate it and I believe the bug you see might actually be caused by #554. Are you able to replicate it after applying the fix?

**Comment by dynamicplus** [comment] 2015-05-19 09:51
@mbeccati is fix is applied, problem is resolved and calendar/date works

**Comment by mbeccati** [comment] 2015-05-19 09:55
Good. Closing as duplicate of #554

**Closed by mbeccati** 2015-05-19 09:55 UTC
Labels: Question
