### ISSUE TITLE
Indexed Columns are being skipped when using OA_factoryDO::insert()

### ISSUE THREAD

**Issue by knife-dev** [revive-adserver/revive-adserver#1135] opened 2019-12-05 17:06 UTC
I am using/found this bug on Revive Adserver v5.0.0/v5.0.2

Problem:
The problem is that insert() either update() methods are skipping indexed columns (declared as keys in db_schema.ini) even if they're not declared as autoincrement and by judging at the source code, this shouldn't be like this.

> File: revive-adserver/lib/pear/DB/DataObject.php

```PHP
function insert() {
...
            // if we are  keyusing autoincrement - skip the column...
            if ($key && ($k == $key) && $useNative) {
                OA::debug("pear.insert(): column skipped ($key / $k) $useNative");
                continue;
            }
...
}
```

- Screenshot from debug.log (I modified the DataObject.php in the lib/pear/DB path)
![image](https://user-images.githubusercontent.com/53711246/70248303-74f59080-1759-11ea-9d1d-a7672671c9a5.png)

- Steps to reproduce:
1.- Create a Plugin.
2.- Declare a table XML file with a index/primary key: (example)
```XML
<?xml version="1.0" encoding="UTF-8" ?>
<?xml-stylesheet type="text/xsl" href="xsl/mdb2_schema.xsl"?>
<database>
 <name>myPlugin</name>
 <create>true</create>
 <overwrite>false</overwrite>
 <version>005</version>
 <status>final</status>
 <table>
  <name>campaign_thing</name>
  <declaration>

   <field>
    <name>campaignid</name>
    <type>openads_mediumint</type>
    <length>9</length>
    <notnull>true</notnull>
    <default></default>
   </field>

  <field>
    <name>clientid</name>
    <type>openads_mediumint</type>
    <length>9</length>
    <notnull>true</notnull>
    <default></default>
   </field>

   <field>
    <name>thing</name>
    <type>openads_decimal</type>
    <length>10,6</length>
    <notnull>true</notnull>
    <default>0</default>
   </field>

   <index>
    <name>campaign_thing_pkey</name>
    <primary>true</primary>
    <field>
     <name>campaignid</name>
     <sorting>ascending</sorting>
    </field>
   </index>

  </declaration>
 </table>
</database>
```
3.- Generate DataObjects:
- db_schema.ini
```ini
[campaign_thing]
campaignid = 129
clientid = 129
thing = 129

[campaign_thing__keys]
campaignid = N
```

- Campaign_thing.php
```PHP
<?php
/**
 * Table Definition for campaign_thing
 */
require_once MAX_PATH.'/lib/max/Dal/DataObjects/DB_DataObjectCommon.php';

class DataObjects_Campaign_thing extends DB_DataObjectCommon 
{
    ###START_AUTOCODE
    /* the code below is auto generated do not remove the above tag */

    public $__table = 'campaign_thing';                 // table name
    public $campaignid;                      // MEDIUMINT(9) => openads_mediumint => 129 
    public $clientid;                        // MEDIUMINT(9) => openads_mediumint => 129 
    public $thing;                          // DECIMAL(10,6) => openads_decimal => 129 

    /* Static get */
    function staticGet($k,$v=NULL) { return DB_DataObject::staticGetFromClassName('DataObjects_Campaign_thing',$k,$v); }

    var $defaultValues = array(
                'thing' => 0
                );

    /* the code above is auto generated do not remove the tag below */
    ###END_AUTOCODE
}
?>
```
4.- Try to insert/update a record while setting campaignId:
```PHP
    $doCThing = OA_Dal::factoryDO('campaign_thing');
    $doCThing->get('campaignid', 1);
    $doCThing->campaignid     = 1;
    $doCThing->clientid     = 1;
    $doCThing->thing       = 100;
    $saved                  = $doCThing->save();

```
You'll notice that when using this, the "campaignid" field has been set to zero, resulting in an insertion/update error.

**Comment by mbeccati** [comment] 2019-12-06 10:04
Please try

```
$doCThing = OA_Dal::factoryDO('campaign_thing');
$doCThing->campaignid     = 1;
$doCThing->clientid     = 1;
$doCThing->thing       = 100;
$saved                  = $doCThing->insert();
```

**Comment by mbeccati** [comment] 2019-12-06 10:05
Ok, sorry. You'll need to add something like:

```
    /**
     * Table has no autoincrement/sequence so we override sequenceKey().
     *
     * @return array
     */
    function sequenceKey() {
        return array(false, false, false);
    }
```

**Comment by mbeccati** [comment] 2019-12-06 10:06
Closing. Not a bug.

**Closed by mbeccati** 2019-12-06 10:06 UTC

**Comment by matiasperrone** [comment] 2020-08-07 15:30
Also:

```php
  function keys()
  {
    return [];
  }
```
