### ISSUE TITLE
modifyBanner PUT API request is creating a new banner

### ISSUE THREAD

**Issue by jawadmunir25** [revive-adserver/revive-adserver#1058] opened 2019-05-10 05:12 UTC
Problem:
I have created a banner ad using Revive Adserver's create new banner API call “URL/bnn/new” and when I try to update that particular banner using modify banner a API call “URL/bnn/[bannerId]”, rather than modifying the banner, Revive Adserver always creates a new banner on that "modify banner" request.

Steps To Reproduce:
1. Create a new banner using create new banner API.
2. Update that banner using modify banner API.
3. New banner will be created rather than updating the previous banner.

**Comment by erikgeurts** [comment] 2019-05-10 05:36
This report comes from a user of the [Revive Adserver REST API](https://www.reviveadserverrestapi.com/), a paid add-on for Revive Adserver. The end points the report refers to are from this REST API.

However, the user mentioned in a tech support ticket with the REST API developers that they traced the cause of their issue back to a bug in Revive Adserver itself. They also mentioned they were able to fix that bug.

As such, we've asked them to open an issue here on and if possible provide the fix so it can be incorporated in a future release.

Full disclosure:  [Revive Adserver REST API](https://www.reviveadserverrestapi.com/) is a product sold by my company [Platform IQ](https://www.platformiq.com/).

**Comment by jawadmunir25** [comment] 2019-05-10 05:45
I am the user that made the tech support ticket (Revive adserver REST API).
I would like to provide the fix for the issue.

**Comment by erikgeurts** [comment] 2019-05-10 05:56
Please feel free to create a pull request for your fix.

**Comment by erikgeurts** [comment] 2019-05-11 06:40
We've been unable to replicate the behavior that was mentioned in the comment opening this issue. Modifying an existing banner simply modifies it, as it is supposed to do. Awaiting more specific steps to reproduce the issue, otherwise closing this issue in about 1 week.

**Comment by mbeccati** [comment] 2019-05-11 07:49
I think the original poster was not sending the banner id in the request.

**Closed** 2019-05-17 06:28 UTC
Labels: Invalid
