### ISSUE TITLE
Site Page URL Delivery Limitation not working 

### ISSUE THREAD

**Issue by lludwig** [revive-adserver/revive-adserver#545] opened 2015-05-08 11:57 UTC
When in the admin area of a banner in version 3.2.0 the Site Page URL delivery limitation no longer works. I get this displayed on the screen.

![screen shot 2015-05-08 at 7 57 27 am](https://cloud.githubusercontent.com/assets/49962/7535881/e7f30c44-f557-11e4-86e7-a309aa6645ae.png)

**Comment by erikgeurts** [comment] 2015-05-08 12:58
I've not been able to reproduce this (version 3.2.0 as well):

![image](https://cloud.githubusercontent.com/assets/5102461/7536717/7575982c-f592-11e4-81f0-1f496ed80967.png)

Would it be possible to list more specifically what the steps are that lead to this situation?

**Comment by lludwig** [comment] 2015-05-08 13:00
I'm not sure perhaps it's the settings I'm using on the site? I tried within a Google Adsense and my own inhouse add both lead the same result.

**Comment by erikgeurts** [comment] 2015-05-08 13:02
What you see doesn't have to do with the specific of the ad you're creating and/or modifying, it seems to be related to the code of your own Revive Adserver installation.

What I'm looking for is a step by step description of what you do, eventually leading to this little bit of PHP code being displayed inside your user interface. You could also record a little screencast video and then paste a link to it in this issue.

**Comment by lludwig** [comment] 2015-05-08 13:08
In the upgrade process to 3.2.0 the async plugin was missing. I had to manually remove and reinstall that plugin, perhaps one of the plugins should be removed and reinstalled? Question is I have no idea which?

**Comment by erikgeurts** [comment] 2015-05-08 13:25
There is no such thing as a separate async plugin. Which plugin are you referring to?

**Comment by lludwig** [comment] 2015-05-08 13:26
I found the plugin and removed and reinstalled. I have a newer version of Delivery Limitations Plugin I  now of the plugin 1.3.3. It was 1.3.0 before. I'm not sure why but this upgrade to 3.2.0 didn't properly upgrade the plugins. This appears to have fixed the above issue. I'll remove all plugins and reinstall to make sure everything is working properly in our install.

**Comment by erikgeurts** [comment] 2015-05-08 13:29
OK, thanks for letting us know.

If you still have the debug.log file (in your var folder) from the time you performed the upgrade, you might be able to see some messages about failed plugin upgrades.

I'll close this issue now, since the problem appears to be resolved. If you have any new info, just add it to this issue, and if needed we'll be glad to re-open it.

**Closed by erikgeurts** 2015-05-08 13:29 UTC
Labels: Question
