### ISSUE TITLE
CORS Issue

### ISSUE THREAD

**Issue by lgoehrs** [revive-adserver/revive-adserver#1331] opened 2021-11-17 10:04 UTC
Hello, 

I am facing an issue that I was able to resolve with minimum time: The CORS implementation in Revive is a little bit outdated, and most browser will block the queries. This is because using a AllowOring with a wildcard is now forbidden.

To fix this, I would suggest we replace the following function:

HEllo,
I have found a solution arround CORS issue with this:

I would recommend changing this function in lib/max/Delivery/common.php

/**
 * This function sends the anti-caching headers when called
 *
 */
function MAX_commonSetNoCacheHeaders()
{
    MAX_header('Pragma: no-cache');
    MAX_header('Cache-Control: no-cache, no-store, must-revalidate');
    MAX_header('Expires: 0');

    // Also send default CORS headers
    if (!empty($_SERVER['HTTP_ORIGIN']) && preg_match('#https?://#', $_SERVER['HTTP_ORIGIN'])) {
        MAX_header('Access-Control-Allow-Origin: '.$_SERVER['HTTP_ORIGIN']);
        MAX_header("Access-Control-Allow-Credentials: true");
    }
    else
        MAX_header('Access-Control-Allow-Origin: *');
}

By forcing the current website domain who called us, we fix the CORS issue.

I hope this can be integrated into the main code quickly.

Leo

**Comment by erikgeurts** [comment] 2021-11-17 12:41
Could you please elaborate a bit more about what's the actual problem you're facing?

Also, please feel free to create a pull request for your proposed change.

**Comment by erikgeurts** [comment] 2021-11-17 12:42
This appears to be a duplicate of the comment you added to #1131

**Closed** 2021-11-17 12:43 UTC
Labels: Duplicate

**Comment by mbeccati** [comment] 2021-11-18 08:13
Reopening this, as it seems to be an acceptable improvement. In fact I thought we already did that...

**Comment by mbeccati** [comment] 2021-11-18 08:18
@lgoehrs what queries are currently being blocked?

We already have the "improved" code in asyncspc.php, which should be the only delivery file loaded via XHR.
