### ISSUE TITLE
"secure" cookie parameter is not properly set to allow cookie to be stored

### ISSUE THREAD

**Issue by somsak** [revive-adserver/revive-adserver#1436] opened 2023-08-24 06:03 UTC
ReviveAds version: 5.4.1

We are trying to inspect why delivery capping per visitor is not properly used, and found that the cookie parameter is somewhat hard-coded to has samesite=none, secure = null in all generated PHP in www/delivery.

For example, in  www/delivery/lg.php, MAX_cookieClientCookieSet has "secure" and "samesite" as its 6th and 8th argument, but it was never being called with more than 5 arguments, so the default "null" and "none" are always used.

According to https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie, the "secure" parameter must always be used if setting "samesite=none".

If you inspect this in Chrome developer tools, there will be a small warning signed next to Set-cookie said that having samesite=none without secure is wrong.

And this seems to be the root cause why we can not use delivery capping features, which relies on the use of cookie.

**Comment by mbeccati** [comment] 2023-08-24 11:01
Thanks for your report. Are you actually using HTTPS? I've checked the code and the behaviour seems correct when using any supported PHP version.

If not, I'm afraid there's little we can do.

@erikgeurts We probably will also need to update the requirements and documentation to state that HTTPS is needed for capping and other cookie based features, due to modern browser restrictions on 3rd-party cookies.

**Comment by somsak** [comment] 2023-08-24 14:07
Yes I'm using HTTPS. I set requiredSSL=1 in my configuration file too.

**Comment by mbeccati** [comment] 2023-08-25 07:52
I've just double checked, and `Set-Cookie` headers are sent as expected, e.g. `_OABLOCK[215]=deleted; expires=Thu, 01-Jan-1970 00:00:01 GMT; Max-Age=0; path=/; secure; SameSite=none`

The only explanation is that your setup isn't properly telling PHP / Revive that requests are being made through HTTPS (missing php-fpm directive to set HTTPS=on?). Feel free to check our forums for support, but I'll have to close the issue as this is not a bug.

**Closed by mbeccati** 2023-08-25 07:52 UTC
Labels: Feedback Required

**Comment by erikgeurts** [comment] 2023-09-06 14:58
> @erikgeurts We probably will also need to update the requirements and documentation to state that HTTPS is needed for capping and other cookie based features, due to modern browser restrictions on 3rd-party cookies.

I've added a note on this to the page about the Technical Requirements for Revive Adserver at https://www.revive-adserver.com/support/requirements/
