### ISSUE TITLE
HTML5 Banner with many files

### ISSUE THREAD

**Issue by alexkleinubing** [revive-adserver/revive-adserver#764] opened 2016-09-29 13:16 UTC
In some cases the banner the client wishes for has to be a html banner because it contains an Imagemap or Javascript or just basic HTML. But most of the time these banners do also contain one or more images. With the current html banners in Revive Adserver, someone has to manually upload the banner images somewhere, adjust the banner coede and then create a new banner in revive.

Adobe Animate export HTML5 banners, but dont can use BASE64 for example.Is useful upload files for banner.

**Comment by erikgeurts** [comment] 2016-09-29 13:34
Duplicate of #408

**Closed** 2016-09-29 13:45 UTC
Labels: Duplicate
