### ISSUE TITLE
GeoIP2 - available/unavailable ?

### ISSUE THREAD

**Issue by opensubtitles** [revive-adserver/revive-adserver#1072] opened 2019-07-05 13:09 UTC
currently using Revive Adserver v4.2.1 running on lighttpd 1.4.45, PHP 7.3.0RC4 and MySQL 5.5.5-10.0.30-MariaDB.

MaxMind GeoIP Plugin 1.3.6

downloaded, unpacked, path configured for https://geolite.maxmind.com/download/geoip/database/GeoLite2-Country.tar.gz

But still in banner limitations I can not set GEO

Please help, is GEO2 supported in 4.2.1 or it is not ? If it is, how to configure it ?

**Comment by andrewatfornax** [comment] 2019-07-09 03:57
This is a duplicate of #315. Closing.

**Closed by andrewatfornax** 2019-07-09 03:57 UTC
Labels: Duplicate
