### ISSUE TITLE
Error on Upgrade

### ISSUE THREAD

**Issue by IanSha** [revive-adserver/revive-adserver#939] opened 2018-01-10 18:39 UTC
I was successfully running Revive AdServer. I was prompted to upgrade and followed the process. When clicking on the "final step" for upgrading, I got an error message that it couldn't detect that PHP5.6 was running.

I have been, and am currently, running PHP5.6.

Sorry, but the Revive Adserver installer system cannot currently be started
Detected problem:

    PHP version 5.6.0, or greater, was not detected.

How do I recover my currently running campaigns?

**Comment by Gildus** [comment] 2018-01-16 19:42
Hi, do you have some phpinfo with nginx or apache?

**Comment by mbeccati** [comment] 2018-01-17 09:40
This one seems extremely odd. However, it looks like a support request for our [forums](https://forum.revive-adserver.com), not a bug in Revive Adserver. I'm closing the issue for now. Please reopen if it turns out to be an actual bug.

**Closed by mbeccati** 2018-01-17 09:40 UTC
