### ISSUE TITLE
Not possible install on Debian Stretch MariaDB

### ISSUE THREAD

**Issue by flochman** [revive-adserver/revive-adserver#925] opened 2017-12-11 08:28 UTC
Hi,

I try to install Revive adserver on Linux Debian Stretch under MariaDB but installation failed to create database.

I tried several times.

Thanks.

**Comment by mbeccati** [comment] 2017-12-11 08:39
@flochman I've just tested installation on MariaDB on a Docker instance and I haven't had any issues:
![immagine](https://user-images.githubusercontent.com/282388/33822197-f9aaa8bc-de56-11e7-88db-ceff9963b818.png)
It is not Stretch, but MariaDB's version is apparently newer than what's provided on Stretch itself.

Does the mysql user have permissions to create the database? Can it properly connect? What if you create the database manually?

**Comment by flochman** [comment] 2017-12-11 08:46
@mbeccati 
Yes, I tried create database manually, but no help.

The exact error reporting is this:

"Installation failed to create the core tables"

I use last vesion of ReviveAdserver and default versions of Apache and MariaDB on DEbian Stretch. PHP version is 7.0

Ramdomly it create database but no tables.

**Comment by flochman** [comment] 2017-12-11 08:48
Yes, the mysql user have permissions and connect properly.

**Comment by mbeccati** [comment] 2017-12-11 09:33
@flochman anything in var/debug.log?

**Comment by flochman** [comment] 2017-12-11 09:45
@mbeccati No there is nothing interesting in debug.log

**Comment by mbeccati** [comment] 2017-12-11 09:50
@flochman or install.log

**Comment by flochman** [comment] 2017-12-11 10:05
Ahh, I was looking somewhere diffrent than revive folder

In debug.log there is this:


Dec 11 08:18:09 +0000 OX-5a2e3f16289bc [    error]  Unable to drop table rv_account_preference_assoc
Dec 11 08:18:09 +0000 OX-5a2e3f16289bc [    error]  Unable to drop the table account_preference_assoc
Dec 11 08:18:09 +0000 OX-5a2e3f16289bc [    error]  Unable to drop table rv_account_user_assoc
Dec 11 08:18:09 +0000 OX-5a2e3f16289bc [    error]  Unable to drop the table account_user_assoc
Dec 11 08:18:09 +0000 OX-5a2e3f16289bc [    error]  Unable to drop table rv_account_user_permission_assoc
Dec 11 08:18:09 +0000 OX-5a2e3f16289bc [    error]  Unable to drop the table account_user_permission_assoc
Dec 11 08:18:09 +0000 OX-5a2e3f16289bc [    error]  Unable to drop table rv_accounts
Dec 11 08:18:09 +0000 OX-5a2e3f16289bc [    error]  Unable to drop the table accounts
Dec 11 08:18:09 +0000 OX-5a2e3f16289bc [    error]  Unable to drop table rv_acls
Dec 11 08:18:09 +0000 OX-5a2e3f16289bc [    error]  Unable to drop the table acls
Dec 11 08:18:09 +0000 OX-5a2e3f16289bc [    error]  Unable to drop table rv_acls_channel
Dec 11 08:18:09 +0000 OX-5a2e3f16289bc [    error]  Unable to drop the table acls_channel
Dec 11 08:18:09 +0000 OX-5a2e3f16289bc [    error]  Unable to drop table rv_ad_category_assoc
Dec 11 08:18:09 +0000 OX-5a2e3f16289bc [    error]  Unable to drop the table ad_category_assoc
Dec 11 08:18:09 +0000 OX-5a2e3f16289bc [    error]  Unable to drop table rv_ad_zone_assoc
Dec 11 08:18:09 +0000 OX-5a2e3f16289bc [    error]  Unable to drop the table ad_zone_assoc
Dec 11 08:18:09 +0000 OX-5a2e3f16289bc [    error]  Unable to drop table rv_affiliates
Dec 11 08:18:09 +0000 OX-5a2e3f16289bc [    error]  Unable to drop the table affiliates
Dec 11 08:18:09 +0000 OX-5a2e3f16289bc [    error]  Unable to drop table rv_affiliates_extra
Dec 11 08:18:09 +0000 OX-5a2e3f16289bc [    error]  Unable to drop the table affiliates_extra
Dec 11 08:18:09 +0000 OX-5a2e3f16289bc [    error]  Unable to drop table rv_agency
Dec 11 08:18:09 +0000 OX-5a2e3f16289bc [    error]  Unable to drop the table agency
Dec 11 08:18:09 +0000 OX-5a2e3f16289bc [    error]  Unable to drop table rv_application_variable
Dec 11 08:18:09 +0000 OX-5a2e3f16289bc [    error]  Unable to drop the table application_variable
Dec 11 08:18:09 +0000 OX-5a2e3f16289bc [    error]  Unable to drop table rv_audit
Dec 11 08:18:09 +0000 OX-5a2e3f16289bc [    error]  Unable to drop the table audit
Dec 11 08:18:09 +0000 OX-5a2e3f16289bc [    error]  Unable to drop table rv_banners
Dec 11 08:18:09 +0000 OX-5a2e3f16289bc [    error]  Unable to drop the table banners
Dec 11 08:18:09 +0000 OX-5a2e3f16289bc [    error]  Unable to drop table rv_campaigns
Dec 11 08:18:09 +0000 OX-5a2e3f16289bc [    error]  Unable to drop the table campaigns
Dec 11 08:18:09 +0000 OX-5a2e3f16289bc [    error]  Unable to drop table rv_campaigns_trackers
Dec 11 08:18:09 +0000 OX-5a2e3f16289bc [    error]  Unable to drop the table campaigns_trackers
Dec 11 08:18:09 +0000 OX-5a2e3f16289bc [    error]  Unable to drop table rv_category
Dec 11 08:18:09 +0000 OX-5a2e3f16289bc [    error]  Unable to drop the table category
Dec 11 08:18:09 +0000 OX-5a2e3f16289bc [    error]  Unable to drop table rv_channel
Dec 11 08:18:09 +0000 OX-5a2e3f16289bc [    error]  Unable to drop the table channel
Dec 11 08:18:09 +0000 OX-5a2e3f16289bc [    error]  Unable to drop table rv_clients
Dec 11 08:18:09 +0000 OX-5a2e3f16289bc [    error]  Unable to drop the table clients
Dec 11 08:18:09 +0000 OX-5a2e3f16289bc [    error]  Unable to drop table rv_data_intermediate_ad
Dec 11 08:18:09 +0000 OX-5a2e3f16289bc [    error]  Unable to drop the table data_intermediate_ad
Dec 11 08:18:09 +0000 OX-5a2e3f16289bc [    error]  Unable to drop table rv_data_intermediate_ad_connection
Dec 11 08:18:09 +0000 OX-5a2e3f16289bc [    error]  Unable to drop the table data_intermediate_ad_connection
Dec 11 08:18:09 +0000 OX-5a2e3f16289bc [    error]  Unable to drop table rv_data_intermediate_ad_variable_value
Dec 11 08:18:09 +0000 OX-5a2e3f16289bc [    error]  Unable to drop the table data_intermediate_ad_variable_value
Dec 11 08:18:09 +0000 OX-5a2e3f16289bc [    error]  Unable to drop table rv_data_raw_ad_click
Dec 11 08:18:09 +0000 OX-5a2e3f16289bc [    error]  Unable to drop the table data_raw_ad_click
Dec 11 08:18:09 +0000 OX-5a2e3f16289bc [    error]  Unable to drop table rv_data_raw_ad_impression
Dec 11 08:18:09 +0000 OX-5a2e3f16289bc [    error]  Unable to drop the table data_raw_ad_impression
Dec 11 08:18:09 +0000 OX-5a2e3f16289bc [    error]  Unable to drop table rv_data_raw_ad_request
Dec 11 08:18:09 +0000 OX-5a2e3f16289bc [    error]  Unable to drop the table data_raw_ad_request
Dec 11 08:18:09 +0000 OX-5a2e3f16289bc [    error]  Unable to drop table rv_data_raw_tracker_impression
Dec 11 08:18:09 +0000 OX-5a2e3f16289bc [    error]  Unable to drop the table data_raw_tracker_impression
Dec 11 08:18:09 +0000 OX-5a2e3f16289bc [    error]  Unable to drop table rv_data_raw_tracker_variable_value
Dec 11 08:18:09 +0000 OX-5a2e3f16289bc [    error]  Unable to drop the table data_raw_tracker_variable_value
Dec 11 08:18:09 +0000 OX-5a2e3f16289bc [    error]  Unable to drop table rv_data_summary_ad_hourly
Dec 11 08:18:09 +0000 OX-5a2e3f16289bc [    error]  Unable to drop the table data_summary_ad_hourly
Dec 11 08:18:09 +0000 OX-5a2e3f16289bc [    error]  Unable to drop table rv_data_summary_ad_zone_assoc
Dec 11 08:18:09 +0000 OX-5a2e3f16289bc [    error]  Unable to drop the table data_summary_ad_zone_assoc
Dec 11 08:18:09 +0000 OX-5a2e3f16289bc [    error]  Unable to drop table rv_data_summary_channel_daily
Dec 11 08:18:09 +0000 OX-5a2e3f16289bc [    error]  Unable to drop the table data_summary_channel_daily
Dec 11 08:18:09 +0000 OX-5a2e3f16289bc [    error]  Unable to drop table rv_data_summary_zone_impression_history
Dec 11 08:18:09 +0000 OX-5a2e3f16289bc [    error]  Unable to drop the table data_summary_zone_impression_history
Dec 11 08:18:09 +0000 OX-5a2e3f16289bc [    error]  Unable to drop table rv_images
Dec 11 08:18:09 +0000 OX-5a2e3f16289bc [    error]  Unable to drop the table images
Dec 11 08:18:09 +0000 OX-5a2e3f16289bc [    error]  Unable to drop table rv_log_maintenance_forecasting
Dec 11 08:18:09 +0000 OX-5a2e3f16289bc [    error]  Unable to drop the table log_maintenance_forecasting
Dec 11 08:18:09 +0000 OX-5a2e3f16289bc [    error]  Unable to drop table rv_log_maintenance_priority
Dec 11 08:18:09 +0000 OX-5a2e3f16289bc [    error]  Unable to drop the table log_maintenance_priority
Dec 11 08:18:09 +0000 OX-5a2e3f16289bc [    error]  Unable to drop table rv_log_maintenance_statistics
Dec 11 08:18:09 +0000 OX-5a2e3f16289bc [    error]  Unable to drop the table log_maintenance_statistics
Dec 11 08:18:09 +0000 OX-5a2e3f16289bc [    error]  Unable to drop table rv_password_recovery
Dec 11 08:18:09 +0000 OX-5a2e3f16289bc [    error]  Unable to drop the table password_recovery
Dec 11 08:18:09 +0000 OX-5a2e3f16289bc [    error]  Unable to drop table rv_placement_zone_assoc
Dec 11 08:18:09 +0000 OX-5a2e3f16289bc [    error]  Unable to drop the table placement_zone_assoc
Dec 11 08:18:09 +0000 OX-5a2e3f16289bc [    error]  Unable to drop table rv_preferences
Dec 11 08:18:09 +0000 OX-5a2e3f16289bc [    error]  Unable to drop the table preferences
Dec 11 08:18:09 +0000 OX-5a2e3f16289bc [    error]  Unable to drop table rv_session
Dec 11 08:18:09 +0000 OX-5a2e3f16289bc [    error]  Unable to drop the table session
Dec 11 08:18:09 +0000 OX-5a2e3f16289bc [    error]  Unable to drop table rv_targetstats
Dec 11 08:18:09 +0000 OX-5a2e3f16289bc [    error]  Unable to drop the table targetstats
Dec 11 08:18:09 +0000 OX-5a2e3f16289bc [    error]  Unable to drop table rv_tracker_append
Dec 11 08:18:09 +0000 OX-5a2e3f16289bc [    error]  Unable to drop the table tracker_append
Dec 11 08:18:09 +0000 OX-5a2e3f16289bc [    error]  Unable to drop table rv_trackers
Dec 11 08:18:09 +0000 OX-5a2e3f16289bc [    error]  Unable to drop the table trackers
Dec 11 08:18:09 +0000 OX-5a2e3f16289bc [    error]  Unable to drop table rv_userlog
Dec 11 08:18:09 +0000 OX-5a2e3f16289bc [    error]  Unable to drop the table userlog
Dec 11 08:18:09 +0000 OX-5a2e3f16289bc [    error]  Unable to drop table rv_users
Dec 11 08:18:09 +0000 OX-5a2e3f16289bc [    error]  Unable to drop the table users
Dec 11 08:18:09 +0000 OX-5a2e3f16289bc [    error]  Unable to drop table rv_variable_publisher
Dec 11 08:18:09 +0000 OX-5a2e3f16289bc [    error]  Unable to drop the table variable_publisher
Dec 11 08:18:09 +0000 OX-5a2e3f16289bc [    error]  Unable to drop table rv_variables
Dec 11 08:18:09 +0000 OX-5a2e3f16289bc [    error]  Unable to drop the table variables
Dec 11 08:18:09 +0000 OX-5a2e3f16289bc [    error]  Unable to drop table rv_zones
Dec 11 08:18:09 +0000 OX-5a2e3f16289bc [    error]  Unable to drop the table zones
Dec 11 08:18:10 +0000 OX-5a2e3f16289bc [    error]  Unable to create the table application_variable
Dec 11 08:18:10 +0000 OX-5a2e3f16289bc [    error]  _doQuery: [Error message: Could not execute statement]
[Last executed query: CREATE TABLE `rv_application_variable` (`name` VARCHAR(255) DEFAULT '' NOT NULL, `value` TEXT NOT NULL, PRIMARY KEY (name)) ENGINE = MYISAM]
[Native code: 1071]
[Native message: Specified key was too long; max key length is 1000 bytes]

In install.log

Installation started 2017-12-11 09:57:45
Attempting to connect to database revive with user phpmyadmin
Database created revive
Connected to database revive
Database settings and permissions are OK
creating upgrade_action audit table
successfully created upgrade_action audit table
creating database_action audit table
successfully created database_action audit table
schema definition from cache TRUE

**Comment by mbeccati** [comment] 2017-12-11 10:34
Closing as duplicate of #740 

The suggestion remains: please create the database manually using utf8 as charset rather than utf8mb4.

**Closed by mbeccati** 2017-12-11 10:34 UTC
Labels: Duplicate
