### ISSUE TITLE
migrate to pdo or mysqli

### ISSUE THREAD

**Issue by camaran** [revive-adserver/revive-adserver#661] opened 2016-01-14 08:02 UTC
It's possible to migrate to pdo or mysqli for more php7 compatibility?

**Comment by erikgeurts** [comment] 2016-01-14 08:13
duplicate of #652 ?

**Comment by dkulyk** [comment] 2016-03-02 20:59
Use http://git.php.net/?p=pecl/database/mysql.git for php7

**Comment by mbeccati** [comment] 2016-03-02 21:08
Yes, I believe we should write a little guide for it. The folks at php.net think that making an actual pecl release would delay the move away from ext/mysql, but I'll keep trying to see if I can get it happening.

**Comment by dkisselev** [comment] 2016-03-03 23:48
I wouldn't say this is a duplicate, this is a specific suggestion to move away from mysql_ in the future, and a good place for the discussion around it (the previous issue was support for someone trying to use the current release with php7).

Is there any technical reason behind not migrating to mysqli or PDO? The APIs are very similar and mysql_ has been deprecated for a very long time.

**Comment by samizarraa** [comment] 2016-08-06 09:08
Please migrate to pdo or mysqli for more php7 compatibility!

**Comment by mbeccati** [comment] 2016-09-12 18:21
Fixed in d0495c3be5fd63f8be7d189a3f9764ed6e578483 w/ support for mysqli, thanks to @sgreiner

**Closed by mbeccati** 2016-09-12 18:21 UTC
