### ISSUE TITLE
Emails are not sending from docker container on revive version 5.4

### ISSUE THREAD

**Issue by PHBell** [revive-adserver/revive-adserver#1368] opened 2022-04-25 11:52 UTC
### Problem:
I am currently attempting to set up a revive adserver 5.4 installation inside an alpine docker container, the installation runs smoothly and everything seems to be working correctly. The issue arises when creating a new user, I am prompted that the user will receive an email to complete setting up their account however no email is ever received by the user.

To my understanding revive uses the normal php mail function and I have tested sending a mail both through msmtp and using phps mail function and both are able to send emails.

### Steps To Reproduce:

**1) Clone the following repository https://github.com/dustin-hawkins/ReviveDockerImage with this command:**
git clone git@github.com:dustin-hawkins/ReviveDockerImage.git

**2) Update the dockerfile to the following:**
```
FROM alpine
MAINTAINER jdhawk <jdhawk@dh0.net>

WORKDIR /var/www/html

RUN apk --update upgrade && apk update && apk add curl ca-certificates && update-ca-certificates --fresh && apk add openssl && apk add msmtp && touch /etc/msmtprc

RUN apk --update add \
    --repository http://dl-cdn.alpinelinux.org/alpine/edge/main \
    --repository http://dl-cdn.alpinelinux.org/alpine/edge/community \
        nginx \
        gzip \
        php7 \
        php7-dom \
        php7-ctype \
        php7-curl \
        php7-fpm \
        php7-gd \
        php7-intl \
        php7-json \
        php7-mbstring \
        php7-mcrypt \
        php7-mysqli \
        php7-mysqlnd \
        php7-opcache \
        php7-pdo \
        php7-pdo_mysql \
        php7-posix \
        php7-session \
        php7-xml \
        php7-iconv \
        php7-phar \
        php7-openssl \
        php7-zlib \
        php7-zip \
    && rm -rf /var/cache/apk/*

RUN wget -qO- https://download.revive-adserver.com/revive-adserver-5.4.0.tar.gz | tar xz --strip 1 \
    && chown -R nobody:nobody . \
    && rm -rf /var/cache/apk/*

COPY nginx/nginx.conf /etc/nginx/nginx.conf
COPY ssmtp/msmtprc /etc/msmtprc
COPY php/msmtp.ini /etc/php7/conf.d/msmtp.ini

RUN chmod 600 /etc/msmtprc

RUN mkdir -p /run/nginx

EXPOSE 80

CMD php-fpm7 && nginx -g 'daemon off;'
```

**3) Create a folder named ssmtp and add a file named msmtprc inside**

**4) Using a gmail account with 2 factor authentication enabled navigate to the security settings and add an app password** 

**5) Add the following content to the msmtprc file and substituent [my email] and [my app password] with the gmail address and app 
password respectively:**
```
account default
host smtp.gmail.com
port 587
tls on
tls_starttls on
tls_trust_file /etc/ssl/certs/ca-certificates.crt
tls_certcheck off
auth on
user [my email]
password [my app password]
from [my email]
logfile /var/log/msmtp.log
```

**5) Create a folder named php and add a file named msmtp.ini inside**

**6) Add the following content to the msmtp.ini file**
```
sendmail_path = /usr/bin/msmtp -t
```

**7) Run docker-compose up and setup revive adserver**

**8) While logged in as the admin user create a new user , the user will be created however no email will be sent to the new user** 

**9) sending a mail with msmtp and php can be tested with the following commands:**
```
echo -e "Subject: Test Mail\r\n\r\nThis is a test mail, let me know if this works" |msmtp --debug --from [me@email.com] -t [to@email.com]

php7 -r "mail('[to@email.com]','Test Mail from PHP', 'This is a test mail from PHP, let me know if this works');"
```

**Comment by mbeccati** [comment] 2022-04-28 08:01
Thanks for the report. However, we're not responsible for third party docker images. I have developed and tested the functionality myself on a local docker php-apache image using postfix so I can tell it's not a bug in Revive.

I would suggest checking the logs, opening an issue on the docker image repo and/or trying our forums. Perhaps the email is delivered but is identified as spam, or maybe it is rejected for whatever reason.

Closing, sorry.

**Closed by mbeccati** 2022-04-28 08:01 UTC

**Comment by erikgeurts** [comment] 2022-04-28 08:07
I'd like to add a note to this. As clearly mentioned on our site, we recommend downloading our software *only* from https://www.revive-adserver.com/download/ . Any auto-installer or, as you've seen, this unofficial docker image, could be corrupted, tainted with extra bits of malicious code, or just buggy. Moreover, a big downside of such auto-installers is that these often make it virtually impossible to perform future updates.

Official installation instructions are at https://www.revive-adserver.com/how-to/install/ and official update instructions can be found at https://www.revive-adserver.com/how-to/update/ .
