### ISSUE TITLE
Delivery of HTML banner in HTTPS fail

### ISSUE THREAD

**Issue by chennaor2** [revive-adserver/revive-adserver#821] opened 2017-03-23 11:12 UTC
working with
Adserver v3.0.2 running on Apache 2.2.15, PHP 5.3.3 and Postgres 9.3.12
Moving the server to HTTPS, and the HTML banners stop delivering.
I checked the code and found, that:
file: ./www/delivery/ajs.php
The html_ssl_unsafe contain a boolean value of true or false.
In postgres it is 't' or 'f'
The condition check in php is not working:

here is the work around I made:

added it as the first bit code in the while loop which appears on lines 949, 1020. 1063, 1109
while ($aAd = OA_Dal_Delivery_fetchAssoc($rAds)) {

added the following code:
if ( $aAd['html_ssl_unsafe'] == 't' ){
    $aAd['html_ssl_unsafe'] = TRUE;
} else if ( $aAd['html_ssl_unsafe'] == 'f' ){
    $aAd['html_ssl_unsafe'] = FALSE;
}

if ( $aAd['url_ssl_unsafe'] == 't' ){
    $aAd['url_ssl_unsafe'] = TRUE;
} else if ( $aAd['url_ssl_unsafe'] == 'f' ){
    $aAd['url_ssl_unsafe'] = FALSE;
}

I checked the code of version 4, it is the same.

Thanks

Chen Naor

**Comment by mbeccati** [comment] 2017-04-06 08:08
It's been fixed almost 3 years ago. Closing as duplicate of #352 

In general, please please test the latest release before reporting an issue in order to avoid wasting everyone's time.

**Closed by mbeccati** 2017-04-06 08:08 UTC
