### ISSUE TITLE
Auth incompatible with Percona 5.6.19 and up

### ISSUE THREAD

**Issue by Genda1ph** [revive-adserver/revive-adserver#843] opened 2017-05-02 10:35 UTC
Hello

The `checkPassword` function (`lib/OX/Extension/authentication/authentication.php:100`) fails to acquire a lock in current Percona versions. Specifically, `GET_LOCK` fails with a message

~~~~txt
May 02 09:53:28 +0000 OX-590857184ae41 [  warning]  mysqli_query(): (42000/3057): Incorrect user-level lock name 'OA_auth.1c9a9d1136beeb67b5f78ab5f07041d6.ed6f47d18f7214123a8bd09684611133a5a421e8'.
~~~~

Which causes this error https://monosnap.com/file/qJZVSa4zzHtpLhgnbVY5pWpd3bHLQ7

Warning pops up upon every login (or almost every), but the login issue is transient - not all sessions are affected by this bug, sometimes it's enough to just open an Incognito window for it to work just fine, sometimes whole offices can be affected and nothing helps.

The bug is caused by Percona's implementation of `GET_LOCK` that was introduced around 5.6.19 and this bug [has been filed to Percona](https://bugs.launchpad.net/percona-server/+bug/1555503) team, but I'm not sure when they'll fix it.

I was able to circumvent the issue like this

~~~~patch
--- /home/gendalph/mysqli.php.bak	2017-05-01 16:41:48.823097703 +0000
+++ /home/gendalph/mysqli.php	2017-05-01 16:41:53.575045423 +0000
@@ -30,7 +30,7 @@
     {
         // Acquire lock
         $iAcquired = $this->oDbh->extended->getOne(
-            "SELECT GET_LOCK('$this->_sId', $iWaitTime)",
+            "SELECT GET_LOCK('" + substr($this->_sId, 0, 63) + "', $iWaitTime)",
             'integer'
         );
 
@@ -46,7 +46,7 @@
     {
         // Relase lock
         $iReleased = $this->oDbh->extended->getOne(
-            "SELECT RELEASE_LOCK('$this->_sId')",
+            "SELECT RELEASE_LOCK('" + substr($this->_sId, 0, 63) + "')",
             'integer'
         );
~~~~

But I don't think this is a proper solution and there where a number of other issues, so in the end I had to use a separate Percona 5.5 instance.

I think it would be better to tweak Revive a bit so users won't encounter this issue.

Software versions used:

~~~~
Ubuntu 16.04
apache2                     2.4.18-2ubuntu3 (stock)
libapache2-mod-php          1:7.0+35ubuntu6 (stock w/ stock extensions)
percona-server-server-5.7   5.7.17-11-1.xenial (official Percona repo)
nginx-extras                1.10.1-3+xenial2 (Nginx Stable PPA)
~~~~

**Comment by mbeccati** [comment] 2017-05-03 05:10
Duplicate of #811

**Closed by mbeccati** 2017-05-03 05:10 UTC
