### ISSUE TITLE
site page url errors

### ISSUE THREAD

**Issue by johnfreson** [revive-adserver/revive-adserver#560] opened 2015-05-20 09:59 UTC
Hello,

I have upgraded Revive from 3.05 to 3.2.0 and im getting many problems to use it.
In this case i'm trying to set delivery site page-url filters to any targeting, channel or banner, but i always get same error... i can´t select any values from drop down list because it's empty.

Any solution? Thanks in advance.

PD: I must clarify that I am not a developer
![captura de pantalla 2015-05-20 a la s 11 43 55](https://cloud.githubusercontent.com/assets/10559606/7723223/61b66196-fee7-11e4-918b-6e33e5891b52.png)
, app management only.

**Comment by mbeccati** [comment] 2015-05-26 19:15
Looks like a duplicate of #549, but will investigate

**Comment by mbeccati** [comment] 2015-05-27 07:46
Confirmed. Closing as duplicate.

**Closed by mbeccati** 2015-05-27 07:46 UTC
Labels: Duplicate
