### ISSUE TITLE
Question/help: How to build the product version from the github development source?

### ISSUE THREAD

**Issue by ppvastar** [revive-adserver/revive-adserver#1156] opened 2020-02-13 03:20 UTC
Sorry for asking such question here but I need some help:

After making changes/customizations on the source code from github, how can I build the product for install on a server?

I could not find out any hint on README or the website document. Any hint is appreciated!

**Comment by andrewatfornax** [comment] 2020-02-13 04:19
Closing - not a bug. Please ask support questions in the forums.

But.... https://documentation.revive-adserver.com/display/DOCS/Developer+Guide

**Closed by andrewatfornax** 2020-02-13 04:19 UTC
