### ISSUE TITLE
Compatibility with PHP 7.1.x

### ISSUE THREAD

**Issue by erikgeurts** [revive-adserver/revive-adserver#837] opened 2017-04-17 07:46 UTC
A user reported an issue with Revive Adserver when he upgraded PHP from 5.x to 7.1.0.

**Comment by erikgeurts** [comment] 2017-04-17 07:46
For reference, see https://forum.revive-adserver.com/topic/4487-blank-pages-in-revive-banner-pages-after-upgrade/

**Comment by mbeccati** [comment] 2017-04-18 08:15
Duplicate of #787

**Closed by mbeccati** 2017-04-18 08:15 UTC
