### ISSUE TITLE
Companion banner not coming in response for video ads

### ISSUE THREAD

**Issue by krish512** [revive-adserver/revive-adserver#952] opened 2018-02-12 13:22 UTC
I've created a new website with fresh campaign and zone id. After adding a Inline Video Ad (pre/mid/post-roll) banner, I added a companion banner and linked it with this video banner, screenshot attached,
![image](https://user-images.githubusercontent.com/6457418/36098604-8cca3edc-1025-11e8-93e4-e88552e4d7ba.png)

When I hit my revive url for vast tag, it returns the vast tag without the companion banner section in it. I tried using different types of companion banners but none showed up in the response XML.

I've reduced caching time to 1 second for banners, also every other change reflects immediately. I tried deleting the cache manually by clearing /var/cache folder entirely.

I checked the plugin code, it sends the bannerid request for companion banner correctly to Max_adSelect function but returned value is {"html": ""}, the banner has html value correctly and appears fine when directly configured with a zone id, just doesn't come as a companion banner for vast tag.

Issue created as per the forum post,
[https://forum.revive-adserver.com/topic/4962-companion-banner-not-coming-in-response-for-video-ads/](https://forum.revive-adserver.com/topic/4962-companion-banner-not-coming-in-response-for-video-ads/)

**Comment by mbeccati** [comment] 2018-02-14 08:38
Works for me (HTML5 banner used as companion).

![immagine](https://user-images.githubusercontent.com/282388/36194591-91dd8fdc-116a-11e8-80ac-20d79a5d658e.png)

There must be something in your campaign or banner setup preventing the banner from being selected.

I'm closing the issue for now. Please reopen if you find evidence about this being an actual bug.

**Closed by mbeccati** 2018-02-14 08:38 UTC

**Comment by krish512** [comment] 2018-02-14 08:55
I found the exact bug,

When I enter the banner URL **with HTTPS** or **without HTTP**, it appears fine.
Eg., https://rappio.forkcdn.com/assets/testBanner/300x120.jpg

When I enter the banner URL as http://rappio.forkcdn.com/assets/testBanner/300x120.jpg, the companion banner does not appear. I saw the label as "Image URL (incl. http://)" and hence added http for my banner while testing and could not find the exact issue.

This is a genuine bug, please do not close this.

**Comment by mbeccati** [comment] 2018-02-14 08:57
@krish512 it is not a bug: plain http resources cannot be served over SSL, thus excluded from ad selection. In fact, it is a feature.

**Comment by krish512** [comment] 2018-02-14 09:18
Ok, thanks a lot for the help. I think the label should update accordingly for HTTP and HTTPS
"Image URL (incl. https://)"
