### ISSUE TITLE
Requesting all stats displays a blank page

### ISSUE THREAD

**Issue by lkppo** [revive-adserver/revive-adserver#896] opened 2017-10-13 10:54 UTC
Hello,

When I go in stats and pick all stats option, if I request the results in xls it's fine, but if I click on the publisher name I get a blank page.

This happens after I upgraded from 4.0.1 to 4.0.2. I have reinstalled the Banner Delivery Logging Plugin after having cleaned some warnings about old plugins oxMarket, oxMarketMaintenance, oxDelivery, openXWorkflow (some lines forgotten in conf file only).

![plugins_ok](https://user-images.githubusercontent.com/10128284/31543170-4581e234-b015-11e7-9143-23320683890b.png)
![all_stats](https://user-images.githubusercontent.com/10128284/31543010-98ca5af8-b014-11e7-85ff-585fd17304be.png)
![all_stats_blank_page](https://user-images.githubusercontent.com/10128284/31543011-98f1b2d8-b014-11e7-9f60-c16da45dcaa9.png)

Regards,

-- 
Stéphane Aulery
Développeur
Narbonne Accessoires

**Comment by mbeccati** [comment] 2017-10-16 10:04
Hmm, I don't think the "OpenX Market Advertiser" is supposed to be there. That makes me think that you haven't performed a proper upgrade and/or something went wrong. I'm closing the issue as this is not a bug, please use the forums for support requests. If you have evdence that this is a bug, feel free to reopen and comment here.

**Closed by mbeccati** 2017-10-16 10:04 UTC
